### ISSUE TITLE
Doesn't respect .editorconfig options

### ISSUE THREAD

**Issue by ahmedelgabri** [kewah/vim-cssfmt#1]
[cssfmt 1.3.0](https://github.com/morishitter/cssfmt/releases/tag/v1.3.0) picks up `indent_style` and `indent_size` from `.editorconfig` if you have one in your project otherwise it uses its default settings  [`.editorconfig`](https://github.com/morishitter/cssfmt/blob/master/.editorconfig).

And this works fine from the CLI but when used through the plugin it doesn't respect this and even editing `cssfmt`'s `.editorconfig` itself still the plugin doesn't respect this, I assume it picks these options from my vim settings instead but this will not always be the case since not all projects have the same rules.

Would be nice if it can respect these settings.

**Comment by kewah** [comment]
Thanks for reporting this issue. It seems to be an issue on cssfmt, I've submitted a PR that should fix it.

**Comment by ahmedelgabri** [comment]
Great, thanks

Sent from my iPhone




On Thu, Nov 5, 2015 at 8:32 AM -0800, "Antoine Lehurt" <notifications@github.com> wrote:












Thanks for reporting this issue. It seems to be an issue on cssfmt, I've submitted a PR that should fix it.

**Comment by kewah** [comment]
Let me know if you still have this issue

**Comment by ahmedelgabri** [comment]
Working perfectly now :+1: thanks!
