### ISSUE TITLE
Using `$d` would break the marks

### ISSUE THREAD

**Issue by chemzqm** [kewah/vim-cssfmt#2]
At line https://github.com/kewah/vim-cssfmt/blob/master/plugin/cssfmt.vim#L43

After the format, when user use command like `ctrl-o`, vim would throw an error:

    E19:  Mark has invalid line number

A solution could be 
```
let list = split(output, "\n")
call setline(1, list[0])
call append(1, list[1:])
```
This replace the first line at first.

**Comment by kewah** [comment]
Thanks for the report :+1: Feel free to submit a PR :)
